image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.3"
  ANDROID_SDK_TOOLS: "4333796" # 26.1.1

  GIT_STRATEGY: clone

before_script:
  - apt-get --quiet update --yes
  - wget --quiet --output-document=android-sdk-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -q android-sdk-linux.zip -d android-sdk-linux
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "platforms;android-${ANDROID_COMPILE_SDK}" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "platform-tools" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "build-tools;${ANDROID_BUILD_TOOLS}" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "extras;android;m2repository" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "extras;google;m2repository" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "emulator" &> /dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager --install "system-images;android-24;default;x86" &> /dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux/
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - export GRADLE_USER_HOME=$PWD/.gradle
  - chmod +x ./gradlew

stages:
  - build
  - release

smoke-build:
  stage: build
  script:
    - ./gradlew assembleDebug

release-alpha:
  stage: release
  only:
    - tags
  script:
    - ./gradlew publishGoogleplayRelease
  artifacts:
    paths:
      - app/build/outputs/apk

release-gold:
  stage: release
  only:
    - web
  script:
    - ./gradlew publishGoogleplayRelease -PreleaseType=production
  artifacts:
    paths:
      - app/build/outputs/apk

cache:
  paths:
    - .gradle/caches/
    - .gradle/wrapper/

#unitTests:
#  stage: test
#  script:
#    - ./gradlew test

#functionalTests:
#  stage: test
#  script:
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android-sdk-linux/tools/bin/sdkmanager --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-${ANDROID_COMPILE_SDK}
#    - echo no | android-sdk-linux/tools/bin/sdkmanager create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
#    - android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew cAT
